// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto/analysis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalysisService_AnalyzePosition_FullMethodName       = "/analysis.AnalysisService/AnalyzePosition"
	AnalysisService_AnalyzePositionStream_FullMethodName = "/analysis.AnalysisService/AnalyzePositionStream"
	AnalysisService_AnalyzeGame_FullMethodName           = "/analysis.AnalysisService/AnalyzeGame"
	AnalysisService_AnalyzeGameStream_FullMethodName     = "/analysis.AnalysisService/AnalyzeGameStream"
	AnalysisService_GetBestMoves_FullMethodName          = "/analysis.AnalysisService/GetBestMoves"
	AnalysisService_HealthCheck_FullMethodName           = "/analysis.AnalysisService/HealthCheck"
)

// AnalysisServiceClient is the client API for AnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AnalysisService provides chess position and game analysis using Stockfish
type AnalysisServiceClient interface {
	// Analyze a single FEN position
	AnalyzePosition(ctx context.Context, in *AnalyzePositionRequest, opts ...grpc.CallOption) (*PositionAnalysis, error)
	// Analyze a position with streaming updates at each depth
	AnalyzePositionStream(ctx context.Context, in *AnalyzePositionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionAnalysis], error)
	// Analyze a full game from PGN
	AnalyzeGame(ctx context.Context, in *AnalyzeGameRequest, opts ...grpc.CallOption) (*GameAnalysis, error)
	// Analyze a full game with streaming progress updates
	AnalyzeGameStream(ctx context.Context, in *AnalyzeGameRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameAnalysisProgress], error)
	// Get best moves for a position (MultiPV analysis)
	GetBestMoves(ctx context.Context, in *GetBestMovesRequest, opts ...grpc.CallOption) (*BestMovesResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type analysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalysisServiceClient(cc grpc.ClientConnInterface) AnalysisServiceClient {
	return &analysisServiceClient{cc}
}

func (c *analysisServiceClient) AnalyzePosition(ctx context.Context, in *AnalyzePositionRequest, opts ...grpc.CallOption) (*PositionAnalysis, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionAnalysis)
	err := c.cc.Invoke(ctx, AnalysisService_AnalyzePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) AnalyzePositionStream(ctx context.Context, in *AnalyzePositionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionAnalysis], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnalysisService_ServiceDesc.Streams[0], AnalysisService_AnalyzePositionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnalyzePositionRequest, PositionAnalysis]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalysisService_AnalyzePositionStreamClient = grpc.ServerStreamingClient[PositionAnalysis]

func (c *analysisServiceClient) AnalyzeGame(ctx context.Context, in *AnalyzeGameRequest, opts ...grpc.CallOption) (*GameAnalysis, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameAnalysis)
	err := c.cc.Invoke(ctx, AnalysisService_AnalyzeGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) AnalyzeGameStream(ctx context.Context, in *AnalyzeGameRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameAnalysisProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnalysisService_ServiceDesc.Streams[1], AnalysisService_AnalyzeGameStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnalyzeGameRequest, GameAnalysisProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalysisService_AnalyzeGameStreamClient = grpc.ServerStreamingClient[GameAnalysisProgress]

func (c *analysisServiceClient) GetBestMoves(ctx context.Context, in *GetBestMovesRequest, opts ...grpc.CallOption) (*BestMovesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BestMovesResponse)
	err := c.cc.Invoke(ctx, AnalysisService_GetBestMoves_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AnalysisService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalysisServiceServer is the server API for AnalysisService service.
// All implementations must embed UnimplementedAnalysisServiceServer
// for forward compatibility.
//
// AnalysisService provides chess position and game analysis using Stockfish
type AnalysisServiceServer interface {
	// Analyze a single FEN position
	AnalyzePosition(context.Context, *AnalyzePositionRequest) (*PositionAnalysis, error)
	// Analyze a position with streaming updates at each depth
	AnalyzePositionStream(*AnalyzePositionRequest, grpc.ServerStreamingServer[PositionAnalysis]) error
	// Analyze a full game from PGN
	AnalyzeGame(context.Context, *AnalyzeGameRequest) (*GameAnalysis, error)
	// Analyze a full game with streaming progress updates
	AnalyzeGameStream(*AnalyzeGameRequest, grpc.ServerStreamingServer[GameAnalysisProgress]) error
	// Get best moves for a position (MultiPV analysis)
	GetBestMoves(context.Context, *GetBestMovesRequest) (*BestMovesResponse, error)
	// Health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedAnalysisServiceServer()
}

// UnimplementedAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalysisServiceServer struct{}

func (UnimplementedAnalysisServiceServer) AnalyzePosition(context.Context, *AnalyzePositionRequest) (*PositionAnalysis, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzePosition not implemented")
}
func (UnimplementedAnalysisServiceServer) AnalyzePositionStream(*AnalyzePositionRequest, grpc.ServerStreamingServer[PositionAnalysis]) error {
	return status.Error(codes.Unimplemented, "method AnalyzePositionStream not implemented")
}
func (UnimplementedAnalysisServiceServer) AnalyzeGame(context.Context, *AnalyzeGameRequest) (*GameAnalysis, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeGame not implemented")
}
func (UnimplementedAnalysisServiceServer) AnalyzeGameStream(*AnalyzeGameRequest, grpc.ServerStreamingServer[GameAnalysisProgress]) error {
	return status.Error(codes.Unimplemented, "method AnalyzeGameStream not implemented")
}
func (UnimplementedAnalysisServiceServer) GetBestMoves(context.Context, *GetBestMovesRequest) (*BestMovesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBestMoves not implemented")
}
func (UnimplementedAnalysisServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAnalysisServiceServer) mustEmbedUnimplementedAnalysisServiceServer() {}
func (UnimplementedAnalysisServiceServer) testEmbeddedByValue()                         {}

// UnsafeAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalysisServiceServer will
// result in compilation errors.
type UnsafeAnalysisServiceServer interface {
	mustEmbedUnimplementedAnalysisServiceServer()
}

func RegisterAnalysisServiceServer(s grpc.ServiceRegistrar, srv AnalysisServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalysisService_ServiceDesc, srv)
}

func _AnalysisService_AnalyzePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzePositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).AnalyzePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_AnalyzePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).AnalyzePosition(ctx, req.(*AnalyzePositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_AnalyzePositionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnalyzePositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnalysisServiceServer).AnalyzePositionStream(m, &grpc.GenericServerStream[AnalyzePositionRequest, PositionAnalysis]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalysisService_AnalyzePositionStreamServer = grpc.ServerStreamingServer[PositionAnalysis]

func _AnalysisService_AnalyzeGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).AnalyzeGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_AnalyzeGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).AnalyzeGame(ctx, req.(*AnalyzeGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_AnalyzeGameStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnalyzeGameRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnalysisServiceServer).AnalyzeGameStream(m, &grpc.GenericServerStream[AnalyzeGameRequest, GameAnalysisProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalysisService_AnalyzeGameStreamServer = grpc.ServerStreamingServer[GameAnalysisProgress]

func _AnalysisService_GetBestMoves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBestMovesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).GetBestMoves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_GetBestMoves_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).GetBestMoves(ctx, req.(*GetBestMovesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalysisService_ServiceDesc is the grpc.ServiceDesc for AnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analysis.AnalysisService",
	HandlerType: (*AnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzePosition",
			Handler:    _AnalysisService_AnalyzePosition_Handler,
		},
		{
			MethodName: "AnalyzeGame",
			Handler:    _AnalysisService_AnalyzeGame_Handler,
		},
		{
			MethodName: "GetBestMoves",
			Handler:    _AnalysisService_GetBestMoves_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AnalysisService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AnalyzePositionStream",
			Handler:       _AnalysisService_AnalyzePositionStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AnalyzeGameStream",
			Handler:       _AnalysisService_AnalyzeGameStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/analysis.proto",
}
