// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/analysis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Move classification enum
type MoveClassification int32

const (
	MoveClassification_CLASSIFICATION_UNKNOWN MoveClassification = 0
	MoveClassification_BRILLIANT              MoveClassification = 1  // Exceptional move, often a sacrifice
	MoveClassification_GREAT                  MoveClassification = 2  // Strong move, well above average
	MoveClassification_BEST                   MoveClassification = 3  // The best move available
	MoveClassification_EXCELLENT              MoveClassification = 4  // Very good move
	MoveClassification_GOOD                   MoveClassification = 5  // Good move
	MoveClassification_BOOK                   MoveClassification = 6  // Opening book move
	MoveClassification_NORMAL                 MoveClassification = 7  // Average move
	MoveClassification_INACCURACY             MoveClassification = 8  // Small mistake
	MoveClassification_MISTAKE                MoveClassification = 9  // Significant mistake
	MoveClassification_BLUNDER                MoveClassification = 10 // Major mistake
	MoveClassification_MISSED_WIN             MoveClassification = 11 // Missed winning opportunity
)

// Enum value maps for MoveClassification.
var (
	MoveClassification_name = map[int32]string{
		0:  "CLASSIFICATION_UNKNOWN",
		1:  "BRILLIANT",
		2:  "GREAT",
		3:  "BEST",
		4:  "EXCELLENT",
		5:  "GOOD",
		6:  "BOOK",
		7:  "NORMAL",
		8:  "INACCURACY",
		9:  "MISTAKE",
		10: "BLUNDER",
		11: "MISSED_WIN",
	}
	MoveClassification_value = map[string]int32{
		"CLASSIFICATION_UNKNOWN": 0,
		"BRILLIANT":              1,
		"GREAT":                  2,
		"BEST":                   3,
		"EXCELLENT":              4,
		"GOOD":                   5,
		"BOOK":                   6,
		"NORMAL":                 7,
		"INACCURACY":             8,
		"MISTAKE":                9,
		"BLUNDER":                10,
		"MISSED_WIN":             11,
	}
)

func (x MoveClassification) Enum() *MoveClassification {
	p := new(MoveClassification)
	*p = x
	return p
}

func (x MoveClassification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MoveClassification) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_analysis_proto_enumTypes[0].Descriptor()
}

func (MoveClassification) Type() protoreflect.EnumType {
	return &file_proto_analysis_proto_enumTypes[0]
}

func (x MoveClassification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MoveClassification.Descriptor instead.
func (MoveClassification) EnumDescriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{0}
}

// Request to analyze a single position
type AnalyzePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fen           string                 `protobuf:"bytes,1,opt,name=fen,proto3" json:"fen,omitempty"`                               // FEN string of the position
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`                          // Analysis depth (10-30)
	MultiPv       int32                  `protobuf:"varint,3,opt,name=multi_pv,json=multiPv,proto3" json:"multi_pv,omitempty"`       // Number of principal variations (1-5)
	TimeoutMs     int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // Timeout in milliseconds (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzePositionRequest) Reset() {
	*x = AnalyzePositionRequest{}
	mi := &file_proto_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzePositionRequest) ProtoMessage() {}

func (x *AnalyzePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzePositionRequest.ProtoReflect.Descriptor instead.
func (*AnalyzePositionRequest) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzePositionRequest) GetFen() string {
	if x != nil {
		return x.Fen
	}
	return ""
}

func (x *AnalyzePositionRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *AnalyzePositionRequest) GetMultiPv() int32 {
	if x != nil {
		return x.MultiPv
	}
	return 0
}

func (x *AnalyzePositionRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// Analysis result for a single position
type PositionAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fen           string                 `protobuf:"bytes,1,opt,name=fen,proto3" json:"fen,omitempty"`                           // FEN of analyzed position
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`                      // Depth reached
	Evaluation    *Evaluation            `protobuf:"bytes,3,opt,name=evaluation,proto3" json:"evaluation,omitempty"`             // Position evaluation
	BestMove      string                 `protobuf:"bytes,4,opt,name=best_move,json=bestMove,proto3" json:"best_move,omitempty"` // Best move in UCI format
	Pv            []string               `protobuf:"bytes,5,rep,name=pv,proto3" json:"pv,omitempty"`                             // Principal variation (best line)
	Nodes         int64                  `protobuf:"varint,6,opt,name=nodes,proto3" json:"nodes,omitempty"`                      // Nodes searched
	Nps           int64                  `protobuf:"varint,7,opt,name=nps,proto3" json:"nps,omitempty"`                          // Nodes per second
	TimeMs        int64                  `protobuf:"varint,8,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`      // Time taken in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionAnalysis) Reset() {
	*x = PositionAnalysis{}
	mi := &file_proto_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionAnalysis) ProtoMessage() {}

func (x *PositionAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionAnalysis.ProtoReflect.Descriptor instead.
func (*PositionAnalysis) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *PositionAnalysis) GetFen() string {
	if x != nil {
		return x.Fen
	}
	return ""
}

func (x *PositionAnalysis) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *PositionAnalysis) GetEvaluation() *Evaluation {
	if x != nil {
		return x.Evaluation
	}
	return nil
}

func (x *PositionAnalysis) GetBestMove() string {
	if x != nil {
		return x.BestMove
	}
	return ""
}

func (x *PositionAnalysis) GetPv() []string {
	if x != nil {
		return x.Pv
	}
	return nil
}

func (x *PositionAnalysis) GetNodes() int64 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *PositionAnalysis) GetNps() int64 {
	if x != nil {
		return x.Nps
	}
	return 0
}

func (x *PositionAnalysis) GetTimeMs() int64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

// Position evaluation
type Evaluation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Score:
	//
	//	*Evaluation_Centipawns
	//	*Evaluation_MateIn
	Score         isEvaluation_Score `protobuf_oneof:"score"`
	IsMate        bool               `protobuf:"varint,3,opt,name=is_mate,json=isMate,proto3" json:"is_mate,omitempty"` // Whether this is a mate score
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evaluation) Reset() {
	*x = Evaluation{}
	mi := &file_proto_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evaluation) ProtoMessage() {}

func (x *Evaluation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evaluation.ProtoReflect.Descriptor instead.
func (*Evaluation) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *Evaluation) GetScore() isEvaluation_Score {
	if x != nil {
		return x.Score
	}
	return nil
}

func (x *Evaluation) GetCentipawns() int32 {
	if x != nil {
		if x, ok := x.Score.(*Evaluation_Centipawns); ok {
			return x.Centipawns
		}
	}
	return 0
}

func (x *Evaluation) GetMateIn() int32 {
	if x != nil {
		if x, ok := x.Score.(*Evaluation_MateIn); ok {
			return x.MateIn
		}
	}
	return 0
}

func (x *Evaluation) GetIsMate() bool {
	if x != nil {
		return x.IsMate
	}
	return false
}

type isEvaluation_Score interface {
	isEvaluation_Score()
}

type Evaluation_Centipawns struct {
	Centipawns int32 `protobuf:"varint,1,opt,name=centipawns,proto3,oneof"` // Score in centipawns (positive = white better)
}

type Evaluation_MateIn struct {
	MateIn int32 `protobuf:"varint,2,opt,name=mate_in,json=mateIn,proto3,oneof"` // Mate in N moves (positive = white mates, negative = black mates)
}

func (*Evaluation_Centipawns) isEvaluation_Score() {}

func (*Evaluation_MateIn) isEvaluation_Score() {}

// Request to analyze a full game
type AnalyzeGameRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GameId           string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                                  // Game identifier
	Pgn              string                 `protobuf:"bytes,2,opt,name=pgn,proto3" json:"pgn,omitempty"`                                                      // PGN of the game
	Depth            int32                  `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`                                                 // Analysis depth per move
	MultiPv          int32                  `protobuf:"varint,4,opt,name=multi_pv,json=multiPv,proto3" json:"multi_pv,omitempty"`                              // MultiPV for each position
	IncludeBookMoves bool                   `protobuf:"varint,5,opt,name=include_book_moves,json=includeBookMoves,proto3" json:"include_book_moves,omitempty"` // Analyze opening book moves
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AnalyzeGameRequest) Reset() {
	*x = AnalyzeGameRequest{}
	mi := &file_proto_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeGameRequest) ProtoMessage() {}

func (x *AnalyzeGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeGameRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyzeGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *AnalyzeGameRequest) GetPgn() string {
	if x != nil {
		return x.Pgn
	}
	return ""
}

func (x *AnalyzeGameRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *AnalyzeGameRequest) GetMultiPv() int32 {
	if x != nil {
		return x.MultiPv
	}
	return 0
}

func (x *AnalyzeGameRequest) GetIncludeBookMoves() bool {
	if x != nil {
		return x.IncludeBookMoves
	}
	return false
}

// Full game analysis result
type GameAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Moves         []*MoveAnalysis        `protobuf:"bytes,2,rep,name=moves,proto3" json:"moves,omitempty"`
	WhiteMetrics  *GameMetrics           `protobuf:"bytes,3,opt,name=white_metrics,json=whiteMetrics,proto3" json:"white_metrics,omitempty"`
	BlackMetrics  *GameMetrics           `protobuf:"bytes,4,opt,name=black_metrics,json=blackMetrics,proto3" json:"black_metrics,omitempty"`
	TotalTimeMs   int64                  `protobuf:"varint,5,opt,name=total_time_ms,json=totalTimeMs,proto3" json:"total_time_ms,omitempty"`
	EngineVersion string                 `protobuf:"bytes,6,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAnalysis) Reset() {
	*x = GameAnalysis{}
	mi := &file_proto_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAnalysis) ProtoMessage() {}

func (x *GameAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAnalysis.ProtoReflect.Descriptor instead.
func (*GameAnalysis) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{4}
}

func (x *GameAnalysis) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameAnalysis) GetMoves() []*MoveAnalysis {
	if x != nil {
		return x.Moves
	}
	return nil
}

func (x *GameAnalysis) GetWhiteMetrics() *GameMetrics {
	if x != nil {
		return x.WhiteMetrics
	}
	return nil
}

func (x *GameAnalysis) GetBlackMetrics() *GameMetrics {
	if x != nil {
		return x.BlackMetrics
	}
	return nil
}

func (x *GameAnalysis) GetTotalTimeMs() int64 {
	if x != nil {
		return x.TotalTimeMs
	}
	return 0
}

func (x *GameAnalysis) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

// Analysis progress during game analysis
type GameAnalysisProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GameId          string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	CurrentMove     int32                  `protobuf:"varint,2,opt,name=current_move,json=currentMove,proto3" json:"current_move,omitempty"`              // Current move being analyzed (1-indexed)
	TotalMoves      int32                  `protobuf:"varint,3,opt,name=total_moves,json=totalMoves,proto3" json:"total_moves,omitempty"`                 // Total moves in the game
	ProgressPercent float32                `protobuf:"fixed32,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"` // Progress percentage (0-100)
	MoveAnalysis    *MoveAnalysis          `protobuf:"bytes,5,opt,name=move_analysis,json=moveAnalysis,proto3" json:"move_analysis,omitempty"`            // Analysis of current move (if completed)
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                            // "analyzing", "completed", "error"
	ErrorMessage    string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`            // Error message if status is "error"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GameAnalysisProgress) Reset() {
	*x = GameAnalysisProgress{}
	mi := &file_proto_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAnalysisProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAnalysisProgress) ProtoMessage() {}

func (x *GameAnalysisProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAnalysisProgress.ProtoReflect.Descriptor instead.
func (*GameAnalysisProgress) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *GameAnalysisProgress) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameAnalysisProgress) GetCurrentMove() int32 {
	if x != nil {
		return x.CurrentMove
	}
	return 0
}

func (x *GameAnalysisProgress) GetTotalMoves() int32 {
	if x != nil {
		return x.TotalMoves
	}
	return 0
}

func (x *GameAnalysisProgress) GetProgressPercent() float32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *GameAnalysisProgress) GetMoveAnalysis() *MoveAnalysis {
	if x != nil {
		return x.MoveAnalysis
	}
	return nil
}

func (x *GameAnalysisProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GameAnalysisProgress) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Analysis for a single move in a game
type MoveAnalysis struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MoveNumber     int32                  `protobuf:"varint,1,opt,name=move_number,json=moveNumber,proto3" json:"move_number,omitempty"`                         // Move number (1-indexed)
	Ply            int32                  `protobuf:"varint,2,opt,name=ply,proto3" json:"ply,omitempty"`                                                         // Ply (half-move, 0-indexed)
	Color          string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`                                                      // "white" or "black"
	PlayedMove     string                 `protobuf:"bytes,4,opt,name=played_move,json=playedMove,proto3" json:"played_move,omitempty"`                          // Move played in SAN format
	PlayedMoveUci  string                 `protobuf:"bytes,5,opt,name=played_move_uci,json=playedMoveUci,proto3" json:"played_move_uci,omitempty"`               // Move played in UCI format
	BestMove       string                 `protobuf:"bytes,6,opt,name=best_move,json=bestMove,proto3" json:"best_move,omitempty"`                                // Best move in SAN format
	BestMoveUci    string                 `protobuf:"bytes,7,opt,name=best_move_uci,json=bestMoveUci,proto3" json:"best_move_uci,omitempty"`                     // Best move in UCI format
	FenBefore      string                 `protobuf:"bytes,8,opt,name=fen_before,json=fenBefore,proto3" json:"fen_before,omitempty"`                             // FEN before the move
	FenAfter       string                 `protobuf:"bytes,9,opt,name=fen_after,json=fenAfter,proto3" json:"fen_after,omitempty"`                                // FEN after the move
	EvalBefore     *Evaluation            `protobuf:"bytes,10,opt,name=eval_before,json=evalBefore,proto3" json:"eval_before,omitempty"`                         // Evaluation before the move
	EvalAfter      *Evaluation            `protobuf:"bytes,11,opt,name=eval_after,json=evalAfter,proto3" json:"eval_after,omitempty"`                            // Evaluation after the move
	CentipawnLoss  int32                  `protobuf:"varint,12,opt,name=centipawn_loss,json=centipawnLoss,proto3" json:"centipawn_loss,omitempty"`               // Centipawn loss for this move
	Classification MoveClassification     `protobuf:"varint,13,opt,name=classification,proto3,enum=analysis.MoveClassification" json:"classification,omitempty"` // Move classification
	Pv             []string               `protobuf:"bytes,14,rep,name=pv,proto3" json:"pv,omitempty"`                                                           // Principal variation from this position
	Depth          int32                  `protobuf:"varint,15,opt,name=depth,proto3" json:"depth,omitempty"`                                                    // Depth reached
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MoveAnalysis) Reset() {
	*x = MoveAnalysis{}
	mi := &file_proto_analysis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveAnalysis) ProtoMessage() {}

func (x *MoveAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveAnalysis.ProtoReflect.Descriptor instead.
func (*MoveAnalysis) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{6}
}

func (x *MoveAnalysis) GetMoveNumber() int32 {
	if x != nil {
		return x.MoveNumber
	}
	return 0
}

func (x *MoveAnalysis) GetPly() int32 {
	if x != nil {
		return x.Ply
	}
	return 0
}

func (x *MoveAnalysis) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *MoveAnalysis) GetPlayedMove() string {
	if x != nil {
		return x.PlayedMove
	}
	return ""
}

func (x *MoveAnalysis) GetPlayedMoveUci() string {
	if x != nil {
		return x.PlayedMoveUci
	}
	return ""
}

func (x *MoveAnalysis) GetBestMove() string {
	if x != nil {
		return x.BestMove
	}
	return ""
}

func (x *MoveAnalysis) GetBestMoveUci() string {
	if x != nil {
		return x.BestMoveUci
	}
	return ""
}

func (x *MoveAnalysis) GetFenBefore() string {
	if x != nil {
		return x.FenBefore
	}
	return ""
}

func (x *MoveAnalysis) GetFenAfter() string {
	if x != nil {
		return x.FenAfter
	}
	return ""
}

func (x *MoveAnalysis) GetEvalBefore() *Evaluation {
	if x != nil {
		return x.EvalBefore
	}
	return nil
}

func (x *MoveAnalysis) GetEvalAfter() *Evaluation {
	if x != nil {
		return x.EvalAfter
	}
	return nil
}

func (x *MoveAnalysis) GetCentipawnLoss() int32 {
	if x != nil {
		return x.CentipawnLoss
	}
	return 0
}

func (x *MoveAnalysis) GetClassification() MoveClassification {
	if x != nil {
		return x.Classification
	}
	return MoveClassification_CLASSIFICATION_UNKNOWN
}

func (x *MoveAnalysis) GetPv() []string {
	if x != nil {
		return x.Pv
	}
	return nil
}

func (x *MoveAnalysis) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// Aggregated metrics for a player's side
type GameMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Accuracy          float32                `protobuf:"fixed32,1,opt,name=accuracy,proto3" json:"accuracy,omitempty"`                                            // Accuracy percentage (0-100)
	Acpl              float32                `protobuf:"fixed32,2,opt,name=acpl,proto3" json:"acpl,omitempty"`                                                    // Average centipawn loss
	Blunders          int32                  `protobuf:"varint,3,opt,name=blunders,proto3" json:"blunders,omitempty"`                                             // Number of blunders
	Mistakes          int32                  `protobuf:"varint,4,opt,name=mistakes,proto3" json:"mistakes,omitempty"`                                             // Number of mistakes
	Inaccuracies      int32                  `protobuf:"varint,5,opt,name=inaccuracies,proto3" json:"inaccuracies,omitempty"`                                     // Number of inaccuracies
	GoodMoves         int32                  `protobuf:"varint,6,opt,name=good_moves,json=goodMoves,proto3" json:"good_moves,omitempty"`                          // Number of good moves
	ExcellentMoves    int32                  `protobuf:"varint,7,opt,name=excellent_moves,json=excellentMoves,proto3" json:"excellent_moves,omitempty"`           // Number of excellent moves
	BestMoves         int32                  `protobuf:"varint,8,opt,name=best_moves,json=bestMoves,proto3" json:"best_moves,omitempty"`                          // Number of best moves
	BrilliantMoves    int32                  `protobuf:"varint,9,opt,name=brilliant_moves,json=brilliantMoves,proto3" json:"brilliant_moves,omitempty"`           // Number of brilliant moves
	BookMoves         int32                  `protobuf:"varint,10,opt,name=book_moves,json=bookMoves,proto3" json:"book_moves,omitempty"`                         // Number of book moves
	TotalMoves        int32                  `protobuf:"varint,11,opt,name=total_moves,json=totalMoves,proto3" json:"total_moves,omitempty"`                      // Total moves analyzed
	PerformanceRating int32                  `protobuf:"varint,12,opt,name=performance_rating,json=performanceRating,proto3" json:"performance_rating,omitempty"` // Estimated performance rating
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GameMetrics) Reset() {
	*x = GameMetrics{}
	mi := &file_proto_analysis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMetrics) ProtoMessage() {}

func (x *GameMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMetrics.ProtoReflect.Descriptor instead.
func (*GameMetrics) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{7}
}

func (x *GameMetrics) GetAccuracy() float32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *GameMetrics) GetAcpl() float32 {
	if x != nil {
		return x.Acpl
	}
	return 0
}

func (x *GameMetrics) GetBlunders() int32 {
	if x != nil {
		return x.Blunders
	}
	return 0
}

func (x *GameMetrics) GetMistakes() int32 {
	if x != nil {
		return x.Mistakes
	}
	return 0
}

func (x *GameMetrics) GetInaccuracies() int32 {
	if x != nil {
		return x.Inaccuracies
	}
	return 0
}

func (x *GameMetrics) GetGoodMoves() int32 {
	if x != nil {
		return x.GoodMoves
	}
	return 0
}

func (x *GameMetrics) GetExcellentMoves() int32 {
	if x != nil {
		return x.ExcellentMoves
	}
	return 0
}

func (x *GameMetrics) GetBestMoves() int32 {
	if x != nil {
		return x.BestMoves
	}
	return 0
}

func (x *GameMetrics) GetBrilliantMoves() int32 {
	if x != nil {
		return x.BrilliantMoves
	}
	return 0
}

func (x *GameMetrics) GetBookMoves() int32 {
	if x != nil {
		return x.BookMoves
	}
	return 0
}

func (x *GameMetrics) GetTotalMoves() int32 {
	if x != nil {
		return x.TotalMoves
	}
	return 0
}

func (x *GameMetrics) GetPerformanceRating() int32 {
	if x != nil {
		return x.PerformanceRating
	}
	return 0
}

// Request for MultiPV best moves
type GetBestMovesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fen           string                 `protobuf:"bytes,1,opt,name=fen,proto3" json:"fen,omitempty"`      // FEN string
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // Number of best moves to return (1-10)
	Depth         int32                  `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"` // Analysis depth
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBestMovesRequest) Reset() {
	*x = GetBestMovesRequest{}
	mi := &file_proto_analysis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBestMovesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBestMovesRequest) ProtoMessage() {}

func (x *GetBestMovesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBestMovesRequest.ProtoReflect.Descriptor instead.
func (*GetBestMovesRequest) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{8}
}

func (x *GetBestMovesRequest) GetFen() string {
	if x != nil {
		return x.Fen
	}
	return ""
}

func (x *GetBestMovesRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetBestMovesRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// Response with multiple best moves
type BestMovesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fen           string                 `protobuf:"bytes,1,opt,name=fen,proto3" json:"fen,omitempty"`
	Moves         []*BestMove            `protobuf:"bytes,2,rep,name=moves,proto3" json:"moves,omitempty"`
	Depth         int32                  `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BestMovesResponse) Reset() {
	*x = BestMovesResponse{}
	mi := &file_proto_analysis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BestMovesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BestMovesResponse) ProtoMessage() {}

func (x *BestMovesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BestMovesResponse.ProtoReflect.Descriptor instead.
func (*BestMovesResponse) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{9}
}

func (x *BestMovesResponse) GetFen() string {
	if x != nil {
		return x.Fen
	}
	return ""
}

func (x *BestMovesResponse) GetMoves() []*BestMove {
	if x != nil {
		return x.Moves
	}
	return nil
}

func (x *BestMovesResponse) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// A single best move with evaluation
type BestMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`                     // Rank (1 = best, 2 = second best, etc.)
	MoveUci       string                 `protobuf:"bytes,2,opt,name=move_uci,json=moveUci,proto3" json:"move_uci,omitempty"` // Move in UCI format
	MoveSan       string                 `protobuf:"bytes,3,opt,name=move_san,json=moveSan,proto3" json:"move_san,omitempty"` // Move in SAN format (if available)
	Evaluation    *Evaluation            `protobuf:"bytes,4,opt,name=evaluation,proto3" json:"evaluation,omitempty"`          // Evaluation after this move
	Pv            []string               `protobuf:"bytes,5,rep,name=pv,proto3" json:"pv,omitempty"`                          // Principal variation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BestMove) Reset() {
	*x = BestMove{}
	mi := &file_proto_analysis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BestMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BestMove) ProtoMessage() {}

func (x *BestMove) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BestMove.ProtoReflect.Descriptor instead.
func (*BestMove) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{10}
}

func (x *BestMove) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *BestMove) GetMoveUci() string {
	if x != nil {
		return x.MoveUci
	}
	return ""
}

func (x *BestMove) GetMoveSan() string {
	if x != nil {
		return x.MoveSan
	}
	return ""
}

func (x *BestMove) GetEvaluation() *Evaluation {
	if x != nil {
		return x.Evaluation
	}
	return nil
}

func (x *BestMove) GetPv() []string {
	if x != nil {
		return x.Pv
	}
	return nil
}

// Health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_analysis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{11}
}

// Health check response
type HealthCheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Healthy          bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AvailableWorkers int32                  `protobuf:"varint,3,opt,name=available_workers,json=availableWorkers,proto3" json:"available_workers,omitempty"`
	TotalWorkers     int32                  `protobuf:"varint,4,opt,name=total_workers,json=totalWorkers,proto3" json:"total_workers,omitempty"`
	StockfishVersion string                 `protobuf:"bytes,5,opt,name=stockfish_version,json=stockfishVersion,proto3" json:"stockfish_version,omitempty"`
	UptimeSeconds    int64                  `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_analysis_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{12}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetAvailableWorkers() int32 {
	if x != nil {
		return x.AvailableWorkers
	}
	return 0
}

func (x *HealthCheckResponse) GetTotalWorkers() int32 {
	if x != nil {
		return x.TotalWorkers
	}
	return 0
}

func (x *HealthCheckResponse) GetStockfishVersion() string {
	if x != nil {
		return x.StockfishVersion
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_proto_analysis_proto protoreflect.FileDescriptor

const file_proto_analysis_proto_rawDesc = "" +
	"\n" +
	"\x14proto/analysis.proto\x12\banalysis\"z\n" +
	"\x16AnalyzePositionRequest\x12\x10\n" +
	"\x03fen\x18\x01 \x01(\tR\x03fen\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\x12\x19\n" +
	"\bmulti_pv\x18\x03 \x01(\x05R\amultiPv\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\"\xde\x01\n" +
	"\x10PositionAnalysis\x12\x10\n" +
	"\x03fen\x18\x01 \x01(\tR\x03fen\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\x124\n" +
	"\n" +
	"evaluation\x18\x03 \x01(\v2\x14.analysis.EvaluationR\n" +
	"evaluation\x12\x1b\n" +
	"\tbest_move\x18\x04 \x01(\tR\bbestMove\x12\x0e\n" +
	"\x02pv\x18\x05 \x03(\tR\x02pv\x12\x14\n" +
	"\x05nodes\x18\x06 \x01(\x03R\x05nodes\x12\x10\n" +
	"\x03nps\x18\a \x01(\x03R\x03nps\x12\x17\n" +
	"\atime_ms\x18\b \x01(\x03R\x06timeMs\"k\n" +
	"\n" +
	"Evaluation\x12 \n" +
	"\n" +
	"centipawns\x18\x01 \x01(\x05H\x00R\n" +
	"centipawns\x12\x19\n" +
	"\amate_in\x18\x02 \x01(\x05H\x00R\x06mateIn\x12\x17\n" +
	"\ais_mate\x18\x03 \x01(\bR\x06isMateB\a\n" +
	"\x05score\"\x9e\x01\n" +
	"\x12AnalyzeGameRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x10\n" +
	"\x03pgn\x18\x02 \x01(\tR\x03pgn\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x05R\x05depth\x12\x19\n" +
	"\bmulti_pv\x18\x04 \x01(\x05R\amultiPv\x12,\n" +
	"\x12include_book_moves\x18\x05 \x01(\bR\x10includeBookMoves\"\x98\x02\n" +
	"\fGameAnalysis\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12,\n" +
	"\x05moves\x18\x02 \x03(\v2\x16.analysis.MoveAnalysisR\x05moves\x12:\n" +
	"\rwhite_metrics\x18\x03 \x01(\v2\x15.analysis.GameMetricsR\fwhiteMetrics\x12:\n" +
	"\rblack_metrics\x18\x04 \x01(\v2\x15.analysis.GameMetricsR\fblackMetrics\x12\"\n" +
	"\rtotal_time_ms\x18\x05 \x01(\x03R\vtotalTimeMs\x12%\n" +
	"\x0eengine_version\x18\x06 \x01(\tR\rengineVersion\"\x98\x02\n" +
	"\x14GameAnalysisProgress\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12!\n" +
	"\fcurrent_move\x18\x02 \x01(\x05R\vcurrentMove\x12\x1f\n" +
	"\vtotal_moves\x18\x03 \x01(\x05R\n" +
	"totalMoves\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x02R\x0fprogressPercent\x12;\n" +
	"\rmove_analysis\x18\x05 \x01(\v2\x16.analysis.MoveAnalysisR\fmoveAnalysis\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"\x9c\x04\n" +
	"\fMoveAnalysis\x12\x1f\n" +
	"\vmove_number\x18\x01 \x01(\x05R\n" +
	"moveNumber\x12\x10\n" +
	"\x03ply\x18\x02 \x01(\x05R\x03ply\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x1f\n" +
	"\vplayed_move\x18\x04 \x01(\tR\n" +
	"playedMove\x12&\n" +
	"\x0fplayed_move_uci\x18\x05 \x01(\tR\rplayedMoveUci\x12\x1b\n" +
	"\tbest_move\x18\x06 \x01(\tR\bbestMove\x12\"\n" +
	"\rbest_move_uci\x18\a \x01(\tR\vbestMoveUci\x12\x1d\n" +
	"\n" +
	"fen_before\x18\b \x01(\tR\tfenBefore\x12\x1b\n" +
	"\tfen_after\x18\t \x01(\tR\bfenAfter\x125\n" +
	"\veval_before\x18\n" +
	" \x01(\v2\x14.analysis.EvaluationR\n" +
	"evalBefore\x123\n" +
	"\n" +
	"eval_after\x18\v \x01(\v2\x14.analysis.EvaluationR\tevalAfter\x12%\n" +
	"\x0ecentipawn_loss\x18\f \x01(\x05R\rcentipawnLoss\x12D\n" +
	"\x0eclassification\x18\r \x01(\x0e2\x1c.analysis.MoveClassificationR\x0eclassification\x12\x0e\n" +
	"\x02pv\x18\x0e \x03(\tR\x02pv\x12\x14\n" +
	"\x05depth\x18\x0f \x01(\x05R\x05depth\"\x98\x03\n" +
	"\vGameMetrics\x12\x1a\n" +
	"\baccuracy\x18\x01 \x01(\x02R\baccuracy\x12\x12\n" +
	"\x04acpl\x18\x02 \x01(\x02R\x04acpl\x12\x1a\n" +
	"\bblunders\x18\x03 \x01(\x05R\bblunders\x12\x1a\n" +
	"\bmistakes\x18\x04 \x01(\x05R\bmistakes\x12\"\n" +
	"\finaccuracies\x18\x05 \x01(\x05R\finaccuracies\x12\x1d\n" +
	"\n" +
	"good_moves\x18\x06 \x01(\x05R\tgoodMoves\x12'\n" +
	"\x0fexcellent_moves\x18\a \x01(\x05R\x0eexcellentMoves\x12\x1d\n" +
	"\n" +
	"best_moves\x18\b \x01(\x05R\tbestMoves\x12'\n" +
	"\x0fbrilliant_moves\x18\t \x01(\x05R\x0ebrilliantMoves\x12\x1d\n" +
	"\n" +
	"book_moves\x18\n" +
	" \x01(\x05R\tbookMoves\x12\x1f\n" +
	"\vtotal_moves\x18\v \x01(\x05R\n" +
	"totalMoves\x12-\n" +
	"\x12performance_rating\x18\f \x01(\x05R\x11performanceRating\"S\n" +
	"\x13GetBestMovesRequest\x12\x10\n" +
	"\x03fen\x18\x01 \x01(\tR\x03fen\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x05R\x05depth\"e\n" +
	"\x11BestMovesResponse\x12\x10\n" +
	"\x03fen\x18\x01 \x01(\tR\x03fen\x12(\n" +
	"\x05moves\x18\x02 \x03(\v2\x12.analysis.BestMoveR\x05moves\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x05R\x05depth\"\x9a\x01\n" +
	"\bBestMove\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x19\n" +
	"\bmove_uci\x18\x02 \x01(\tR\amoveUci\x12\x19\n" +
	"\bmove_san\x18\x03 \x01(\tR\amoveSan\x124\n" +
	"\n" +
	"evaluation\x18\x04 \x01(\v2\x14.analysis.EvaluationR\n" +
	"evaluation\x12\x0e\n" +
	"\x02pv\x18\x05 \x03(\tR\x02pv\"\x14\n" +
	"\x12HealthCheckRequest\"\xed\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12+\n" +
	"\x11available_workers\x18\x03 \x01(\x05R\x10availableWorkers\x12#\n" +
	"\rtotal_workers\x18\x04 \x01(\x05R\ftotalWorkers\x12+\n" +
	"\x11stockfish_version\x18\x05 \x01(\tR\x10stockfishVersion\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x03R\ruptimeSeconds*\xbd\x01\n" +
	"\x12MoveClassification\x12\x1a\n" +
	"\x16CLASSIFICATION_UNKNOWN\x10\x00\x12\r\n" +
	"\tBRILLIANT\x10\x01\x12\t\n" +
	"\x05GREAT\x10\x02\x12\b\n" +
	"\x04BEST\x10\x03\x12\r\n" +
	"\tEXCELLENT\x10\x04\x12\b\n" +
	"\x04GOOD\x10\x05\x12\b\n" +
	"\x04BOOK\x10\x06\x12\n" +
	"\n" +
	"\x06NORMAL\x10\a\x12\x0e\n" +
	"\n" +
	"INACCURACY\x10\b\x12\v\n" +
	"\aMISTAKE\x10\t\x12\v\n" +
	"\aBLUNDER\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"MISSED_WIN\x10\v2\xed\x03\n" +
	"\x0fAnalysisService\x12O\n" +
	"\x0fAnalyzePosition\x12 .analysis.AnalyzePositionRequest\x1a\x1a.analysis.PositionAnalysis\x12W\n" +
	"\x15AnalyzePositionStream\x12 .analysis.AnalyzePositionRequest\x1a\x1a.analysis.PositionAnalysis0\x01\x12C\n" +
	"\vAnalyzeGame\x12\x1c.analysis.AnalyzeGameRequest\x1a\x16.analysis.GameAnalysis\x12S\n" +
	"\x11AnalyzeGameStream\x12\x1c.analysis.AnalyzeGameRequest\x1a\x1e.analysis.GameAnalysisProgress0\x01\x12J\n" +
	"\fGetBestMoves\x12\x1d.analysis.GetBestMovesRequest\x1a\x1b.analysis.BestMovesResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.analysis.HealthCheckRequest\x1a\x1d.analysis.HealthCheckResponseB.Z,github.com/eloinsight/analysis-service/protob\x06proto3"

var (
	file_proto_analysis_proto_rawDescOnce sync.Once
	file_proto_analysis_proto_rawDescData []byte
)

func file_proto_analysis_proto_rawDescGZIP() []byte {
	file_proto_analysis_proto_rawDescOnce.Do(func() {
		file_proto_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analysis_proto_rawDesc), len(file_proto_analysis_proto_rawDesc)))
	})
	return file_proto_analysis_proto_rawDescData
}

var file_proto_analysis_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_analysis_proto_goTypes = []any{
	(MoveClassification)(0),        // 0: analysis.MoveClassification
	(*AnalyzePositionRequest)(nil), // 1: analysis.AnalyzePositionRequest
	(*PositionAnalysis)(nil),       // 2: analysis.PositionAnalysis
	(*Evaluation)(nil),             // 3: analysis.Evaluation
	(*AnalyzeGameRequest)(nil),     // 4: analysis.AnalyzeGameRequest
	(*GameAnalysis)(nil),           // 5: analysis.GameAnalysis
	(*GameAnalysisProgress)(nil),   // 6: analysis.GameAnalysisProgress
	(*MoveAnalysis)(nil),           // 7: analysis.MoveAnalysis
	(*GameMetrics)(nil),            // 8: analysis.GameMetrics
	(*GetBestMovesRequest)(nil),    // 9: analysis.GetBestMovesRequest
	(*BestMovesResponse)(nil),      // 10: analysis.BestMovesResponse
	(*BestMove)(nil),               // 11: analysis.BestMove
	(*HealthCheckRequest)(nil),     // 12: analysis.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 13: analysis.HealthCheckResponse
}
var file_proto_analysis_proto_depIdxs = []int32{
	3,  // 0: analysis.PositionAnalysis.evaluation:type_name -> analysis.Evaluation
	7,  // 1: analysis.GameAnalysis.moves:type_name -> analysis.MoveAnalysis
	8,  // 2: analysis.GameAnalysis.white_metrics:type_name -> analysis.GameMetrics
	8,  // 3: analysis.GameAnalysis.black_metrics:type_name -> analysis.GameMetrics
	7,  // 4: analysis.GameAnalysisProgress.move_analysis:type_name -> analysis.MoveAnalysis
	3,  // 5: analysis.MoveAnalysis.eval_before:type_name -> analysis.Evaluation
	3,  // 6: analysis.MoveAnalysis.eval_after:type_name -> analysis.Evaluation
	0,  // 7: analysis.MoveAnalysis.classification:type_name -> analysis.MoveClassification
	11, // 8: analysis.BestMovesResponse.moves:type_name -> analysis.BestMove
	3,  // 9: analysis.BestMove.evaluation:type_name -> analysis.Evaluation
	1,  // 10: analysis.AnalysisService.AnalyzePosition:input_type -> analysis.AnalyzePositionRequest
	1,  // 11: analysis.AnalysisService.AnalyzePositionStream:input_type -> analysis.AnalyzePositionRequest
	4,  // 12: analysis.AnalysisService.AnalyzeGame:input_type -> analysis.AnalyzeGameRequest
	4,  // 13: analysis.AnalysisService.AnalyzeGameStream:input_type -> analysis.AnalyzeGameRequest
	9,  // 14: analysis.AnalysisService.GetBestMoves:input_type -> analysis.GetBestMovesRequest
	12, // 15: analysis.AnalysisService.HealthCheck:input_type -> analysis.HealthCheckRequest
	2,  // 16: analysis.AnalysisService.AnalyzePosition:output_type -> analysis.PositionAnalysis
	2,  // 17: analysis.AnalysisService.AnalyzePositionStream:output_type -> analysis.PositionAnalysis
	5,  // 18: analysis.AnalysisService.AnalyzeGame:output_type -> analysis.GameAnalysis
	6,  // 19: analysis.AnalysisService.AnalyzeGameStream:output_type -> analysis.GameAnalysisProgress
	10, // 20: analysis.AnalysisService.GetBestMoves:output_type -> analysis.BestMovesResponse
	13, // 21: analysis.AnalysisService.HealthCheck:output_type -> analysis.HealthCheckResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_analysis_proto_init() }
func file_proto_analysis_proto_init() {
	if File_proto_analysis_proto != nil {
		return
	}
	file_proto_analysis_proto_msgTypes[2].OneofWrappers = []any{
		(*Evaluation_Centipawns)(nil),
		(*Evaluation_MateIn)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analysis_proto_rawDesc), len(file_proto_analysis_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analysis_proto_goTypes,
		DependencyIndexes: file_proto_analysis_proto_depIdxs,
		EnumInfos:         file_proto_analysis_proto_enumTypes,
		MessageInfos:      file_proto_analysis_proto_msgTypes,
	}.Build()
	File_proto_analysis_proto = out.File
	file_proto_analysis_proto_goTypes = nil
	file_proto_analysis_proto_depIdxs = nil
}
