// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file - run `make proto` to generate actual files

package proto

type AnalyzePositionRequest struct {
	Fen       string
	Depth     int32
	MultiPv   int32
	TimeoutMs int32
}

type PositionAnalysis struct {
	Fen        string
	Depth      int32
	Evaluation *Evaluation
	BestMove   string
	Pv         []string
	Nodes      int64
	Nps        int64
	TimeMs     int64
}

type Evaluation struct {
	Score  isEvaluation_Score
	IsMate bool
}

type isEvaluation_Score interface {
	isEvaluation_Score()
}

type Evaluation_Centipawns struct {
	Centipawns int32
}

type Evaluation_MateIn struct {
	MateIn int32
}

func (*Evaluation_Centipawns) isEvaluation_Score() {}
func (*Evaluation_MateIn) isEvaluation_Score()     {}

type AnalyzeGameRequest struct {
	GameId           string
	Pgn              string
	Depth            int32
	MultiPv          int32
	IncludeBookMoves bool
}

type GameAnalysis struct {
	GameId        string
	Moves         []*MoveAnalysis
	WhiteMetrics  *GameMetrics
	BlackMetrics  *GameMetrics
	TotalTimeMs   int64
	EngineVersion string
}

type GameAnalysisProgress struct {
	GameId          string
	CurrentMove     int32
	TotalMoves      int32
	ProgressPercent float32
	MoveAnalysis    *MoveAnalysis
	Status          string
	ErrorMessage    string
}

type MoveAnalysis struct {
	MoveNumber     int32
	Ply            int32
	Color          string
	PlayedMove     string
	PlayedMoveUci  string
	BestMove       string
	BestMoveUci    string
	FenBefore      string
	FenAfter       string
	EvalBefore     *Evaluation
	EvalAfter      *Evaluation
	CentipawnLoss  int32
	Classification MoveClassification
	Pv             []string
	Depth          int32
}

type MoveClassification int32

const (
	MoveClassification_CLASSIFICATION_UNKNOWN MoveClassification = 0
	MoveClassification_BRILLIANT              MoveClassification = 1
	MoveClassification_GREAT                  MoveClassification = 2
	MoveClassification_BEST                   MoveClassification = 3
	MoveClassification_EXCELLENT              MoveClassification = 4
	MoveClassification_GOOD                   MoveClassification = 5
	MoveClassification_BOOK                   MoveClassification = 6
	MoveClassification_NORMAL                 MoveClassification = 7
	MoveClassification_INACCURACY             MoveClassification = 8
	MoveClassification_MISTAKE                MoveClassification = 9
	MoveClassification_BLUNDER                MoveClassification = 10
	MoveClassification_MISSED_WIN             MoveClassification = 11
)

type GameMetrics struct {
	Accuracy          float32
	Acpl              float32
	Blunders          int32
	Mistakes          int32
	Inaccuracies      int32
	GoodMoves         int32
	ExcellentMoves    int32
	BestMoves         int32
	BrilliantMoves    int32
	BookMoves         int32
	TotalMoves        int32
	PerformanceRating int32
}

type GetBestMovesRequest struct {
	Fen   string
	Count int32
	Depth int32
}

type BestMovesResponse struct {
	Fen   string
	Moves []*BestMove
	Depth int32
}

type BestMove struct {
	Rank       int32
	MoveUci    string
	MoveSan    string
	Evaluation *Evaluation
	Pv         []string
}

type HealthCheckRequest struct{}

type HealthCheckResponse struct {
	Healthy          bool
	Status           string
	AvailableWorkers int32
	TotalWorkers     int32
	StockfishVersion string
	UptimeSeconds    int64
}
