// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a stub file - run `make proto` to generate actual files

package proto

import (
	"context"

	"google.golang.org/grpc"
)

// AnalysisServiceClient is the client API for AnalysisService
type AnalysisServiceClient interface {
	AnalyzePosition(ctx context.Context, in *AnalyzePositionRequest, opts ...grpc.CallOption) (*PositionAnalysis, error)
	AnalyzePositionStream(ctx context.Context, in *AnalyzePositionRequest, opts ...grpc.CallOption) (AnalysisService_AnalyzePositionStreamClient, error)
	AnalyzeGame(ctx context.Context, in *AnalyzeGameRequest, opts ...grpc.CallOption) (*GameAnalysis, error)
	AnalyzeGameStream(ctx context.Context, in *AnalyzeGameRequest, opts ...grpc.CallOption) (AnalysisService_AnalyzeGameStreamClient, error)
	GetBestMoves(ctx context.Context, in *GetBestMovesRequest, opts ...grpc.CallOption) (*BestMovesResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type analysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalysisServiceClient(cc grpc.ClientConnInterface) AnalysisServiceClient {
	return &analysisServiceClient{cc}
}

func (c *analysisServiceClient) AnalyzePosition(ctx context.Context, in *AnalyzePositionRequest, opts ...grpc.CallOption) (*PositionAnalysis, error) {
	return nil, nil
}

func (c *analysisServiceClient) AnalyzePositionStream(ctx context.Context, in *AnalyzePositionRequest, opts ...grpc.CallOption) (AnalysisService_AnalyzePositionStreamClient, error) {
	return nil, nil
}

func (c *analysisServiceClient) AnalyzeGame(ctx context.Context, in *AnalyzeGameRequest, opts ...grpc.CallOption) (*GameAnalysis, error) {
	return nil, nil
}

func (c *analysisServiceClient) AnalyzeGameStream(ctx context.Context, in *AnalyzeGameRequest, opts ...grpc.CallOption) (AnalysisService_AnalyzeGameStreamClient, error) {
	return nil, nil
}

func (c *analysisServiceClient) GetBestMoves(ctx context.Context, in *GetBestMovesRequest, opts ...grpc.CallOption) (*BestMovesResponse, error) {
	return nil, nil
}

func (c *analysisServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	return nil, nil
}

// Stream interfaces
type AnalysisService_AnalyzePositionStreamClient interface {
	Recv() (*PositionAnalysis, error)
	grpc.ClientStream
}

type AnalysisService_AnalyzeGameStreamClient interface {
	Recv() (*GameAnalysisProgress, error)
	grpc.ClientStream
}

// AnalysisServiceServer is the server API for AnalysisService
type AnalysisServiceServer interface {
	AnalyzePosition(context.Context, *AnalyzePositionRequest) (*PositionAnalysis, error)
	AnalyzePositionStream(*AnalyzePositionRequest, AnalysisService_AnalyzePositionStreamServer) error
	AnalyzeGame(context.Context, *AnalyzeGameRequest) (*GameAnalysis, error)
	AnalyzeGameStream(*AnalyzeGameRequest, AnalysisService_AnalyzeGameStreamServer) error
	GetBestMoves(context.Context, *GetBestMovesRequest) (*BestMovesResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedAnalysisServiceServer()
}

// Stream server interfaces
type AnalysisService_AnalyzePositionStreamServer interface {
	Send(*PositionAnalysis) error
	grpc.ServerStream
}

type AnalysisService_AnalyzeGameStreamServer interface {
	Send(*GameAnalysisProgress) error
	grpc.ServerStream
}

// UnimplementedAnalysisServiceServer must be embedded
type UnimplementedAnalysisServiceServer struct{}

func (UnimplementedAnalysisServiceServer) AnalyzePosition(context.Context, *AnalyzePositionRequest) (*PositionAnalysis, error) {
	return nil, nil
}
func (UnimplementedAnalysisServiceServer) AnalyzePositionStream(*AnalyzePositionRequest, AnalysisService_AnalyzePositionStreamServer) error {
	return nil
}
func (UnimplementedAnalysisServiceServer) AnalyzeGame(context.Context, *AnalyzeGameRequest) (*GameAnalysis, error) {
	return nil, nil
}
func (UnimplementedAnalysisServiceServer) AnalyzeGameStream(*AnalyzeGameRequest, AnalysisService_AnalyzeGameStreamServer) error {
	return nil
}
func (UnimplementedAnalysisServiceServer) GetBestMoves(context.Context, *GetBestMovesRequest) (*BestMovesResponse, error) {
	return nil, nil
}
func (UnimplementedAnalysisServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, nil
}
func (UnimplementedAnalysisServiceServer) mustEmbedUnimplementedAnalysisServiceServer() {}

// UnsafeAnalysisServiceServer may be embedded to opt out of forward compatibility
type UnsafeAnalysisServiceServer interface {
	mustEmbedUnimplementedAnalysisServiceServer()
}

// RegisterAnalysisServiceServer registers the server
func RegisterAnalysisServiceServer(s grpc.ServiceRegistrar, srv AnalysisServiceServer) {
	s.RegisterService(&AnalysisService_ServiceDesc, srv)
}

// Service descriptor
var AnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analysis.AnalysisService",
	HandlerType: (*AnalysisServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "proto/analysis.proto",
}
